#!/usr/bin/env bash

set -e
for dir in *; do
  pushd "$dir" &>/dev/null
  nix flake update nixvim-config
  popd &>/dev/null
done

git add .
git commit -m 'chore: update flake lockfiles'
git push origin master
